name: Backstage CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Enable Corepack
      run: |
        corepack enable
        corepack prepare yarn@4.4.1 --activate

    - name: Verify Yarn
      run: yarn --version

    - name: Install Dependencies
      run: yarn install

    - name: Build TypeScript
      run: yarn tsc

    - name: Build Backend
      run: yarn build:backend

    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build . \
          -f packages/backend/Dockerfile \
          -t rajvam6806/backstage:${IMAGE_TAG}

    - name: Push Docker Image
      run: |
        docker push rajvam6806/backstage:${IMAGE_TAG}


    - name: Checkout GitOps Repo
      uses: actions/checkout@v4
      with:
        repository: rajudruva2/eks-gitops-config
        token: ${{ secrets.GH_PAT }}
        path: gitops

    - name: Update Deployment Image Tag
      run: |
        sed -i "s|image: rajvam6806/backstage:.*|image: rajvam6806/backstage:${IMAGE_TAG}|g" \
        gitops/apps/backstage/deployment.yaml

    - name: Commit GitOps Changes
      run: |
        cd gitops

        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add .

        git commit -m "Updated Backstage image to ${IMAGE_TAG}" || echo "No changes"
